services:
  php:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
    extra_hosts:
      - host.containers.internal:host-gateway
    volumes:
      - ./:/www
    ports:
      - target: 80
        published: 8001
        protocol: tcp

  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:9.2
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data_mysql:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:

###> doctrine/doctrine-bundle ###
  database_data_mysql:
###< doctrine/doctrine-bundle ###
