<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20241125085507_2generated extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Set up tables for our entities with MySQL, generated by Doctrine';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE auction_generated_fields (
            id INT AUTO_INCREMENT NOT NULL,
            title VARCHAR(255) generated always as (item->>\'$.title\') stored NOT NULL,
            start_date DATETIME generated always as (item->>\'$.startDate\') stored NOT NULL,
            end_date DATETIME generated always as (item->>\'$.endDate\') stored NOT NULL,
            author VARCHAR(255) generated always as (item->>\'$.author\') stored,
            current_price INT DEFAULT NULL,
            item JSON NOT NULL,
            PRIMARY KEY(id)
        ) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE auction_generated_fields_indexed (
            id INT AUTO_INCREMENT NOT NULL,
            title VARCHAR(255) generated always as (item->>\'$.title\') stored NOT NULL,
            start_date DATETIME generated always as (item->>\'$.startDate\') stored NOT NULL,
            end_date DATETIME generated always as (item->>\'$.endDate\') stored NOT NULL,
            author VARCHAR(255) generated always as (item->>\'$.author\') stored,
            current_price INT DEFAULT NULL,
            item JSON NOT NULL,
            INDEX IDX_D638BFC295275AB8 (start_date),
            INDEX IDX_D638BFC2BDAFD8C8 (author), 
            PRIMARY KEY(id)
        ) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE auction_json (
            id INT AUTO_INCREMENT NOT NULL,
            title VARCHAR(255) NOT NULL,
            start_date DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\',
            end_date DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\',
            current_price INT DEFAULT NULL,
            item JSON NOT NULL,
            PRIMARY KEY(id)
        ) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE auction_json_indexed (
            id INT AUTO_INCREMENT NOT NULL,
            title VARCHAR(255) NOT NULL,
            start_date DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\',
            end_date DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\',
            current_price INT DEFAULT NULL,
            item JSON NOT NULL,
            INDEX IDX_5BF05BCF95275AB8 (start_date),
            PRIMARY KEY(id)
        ) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE auction_generated_fields');
        $this->addSql('DROP TABLE auction_generated_fields_indexed');
        $this->addSql('DROP TABLE auction_json');
        $this->addSql('DROP TABLE auction_json_indexed');
    }
}
