SET SESSION cte_max_recursion_depth = 10000000;

TRUNCATE TABLE auction_json;
INSERT INTO auction_json (title, start_date, end_date, item)
WITH RECURSIVE cnt AS (
    SELECT 1 AS v UNION ALL SELECT v + 1 FROM cnt WHERE v < 10000000
)
SELECT
    CONCAT('Title ', cnt.v),
    DATE_ADD('2024-01-01', INTERVAL cnt.v-1 MINUTE),
    DATE_ADD('2024-01-01', INTERVAL cnt.v+6 MINUTE),
    JSON_OBJECT(
            'type', 'book',
            'genre', CONCAT('Genre ', cnt.v),
            'author', CONCAT('Author ', cnt.v % 1000),
            'title', CONCAT('Title ', cnt.v),
            'description', CONCAT('Description ', cnt.v),
            'startDate', DATE_ADD('2024-01-01', INTERVAL cnt.v-1 MINUTE),
            'endDate', DATE_ADD('2024-01-01', INTERVAL cnt.v+6 MINUTE)
    )
FROM cnt;

TRUNCATE TABLE auction_json_indexed;
INSERT INTO auction_json_indexed (title, start_date, end_date, item)
WITH RECURSIVE cnt AS (
    SELECT 1 AS v UNION ALL SELECT v + 1 FROM cnt WHERE v < 10000000
)
SELECT
    CONCAT('Title ', cnt.v),
    DATE_ADD('2024-01-01', INTERVAL cnt.v-1 MINUTE),
    DATE_ADD('2024-01-01', INTERVAL cnt.v+6 MINUTE),
    JSON_OBJECT(
            'type', 'book',
            'genre', CONCAT('Genre ', cnt.v),
            'author', CONCAT('Author ', cnt.v % 1000),
            'title', CONCAT('Title ', cnt.v),
            'description', CONCAT('Description ', cnt.v),
            'startDate', DATE_ADD('2024-01-01', INTERVAL cnt.v-1 MINUTE),
            'endDate', DATE_ADD('2024-01-01', INTERVAL cnt.v+6 MINUTE)
    )
FROM cnt;

-- the additional columns are generated by mysql (and may not be explicitly assigned a value)
TRUNCATE TABLE auction_generated_fields;
INSERT INTO auction_generated_fields (item)
WITH RECURSIVE cnt AS (
    SELECT 1 AS v UNION ALL SELECT v + 1 FROM cnt WHERE v < 10000000
)
SELECT
    JSON_OBJECT(
            'type', 'book',
            'genre', CONCAT('Genre ', cnt.v),
            'author', CONCAT('Author ', cnt.v % 1000),
            'title', CONCAT('Title ', cnt.v),
            'description', CONCAT('Description ', cnt.v),
            'startDate', DATE_ADD('2024-01-01', INTERVAL cnt.v-1 MINUTE),
            'endDate', DATE_ADD('2024-01-01', INTERVAL cnt.v+6 MINUTE)
    )
FROM cnt;

TRUNCATE TABLE auction_generated_fields_indexed;
INSERT INTO auction_generated_fields_indexed (item)
WITH RECURSIVE cnt AS (
    SELECT 1 AS v UNION ALL SELECT v + 1 FROM cnt WHERE v < 10000000
)
SELECT
    JSON_OBJECT(
            'type', 'book',
            'genre', CONCAT('Genre ', cnt.v),
            'author', CONCAT('Author ', cnt.v % 1000),
            'title', CONCAT('Title ', cnt.v),
            'description', CONCAT('Description ', cnt.v),
            'startDate', DATE_ADD('2024-01-01', INTERVAL cnt.v-1 MINUTE),
            'endDate', DATE_ADD('2024-01-01', INTERVAL cnt.v+6 MINUTE)
    )
FROM cnt;