TRUNCATE TABLE auction_json;
ALTER SEQUENCE auction_json_id_seq RESTART;
INSERT INTO auction_json (title, start_date, end_date, item)
SELECT
    'Title ' || cnt,
    '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt-1)),
    '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt+6)),
    JSON_BUILD_OBJECT(
            'type', 'book',
            'genre', 'Genre '||cnt,
            'author', 'Author ' || cnt % 1000,
            'title', 'Title ' || cnt,
            'description', 'Description ' || cnt,
            'startDate', '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt-1)),
            'endDate', '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt+6))
    )::json
FROM generate_series(1, 10000000) AS t(cnt);

TRUNCATE TABLE auction_json_indexed;
ALTER SEQUENCE auction_json_indexed_id_seq RESTART;
INSERT INTO auction_json_indexed (title, start_date, end_date, item)
SELECT
    'Title ' || cnt,
    '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt-1)),
    '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt+6)),
    JSON_BUILD_OBJECT(
            'type', 'book',
            'genre', 'Genre '||cnt,
            'author', 'Author ' || cnt % 1000,
            'title', 'Title ' || cnt,
            'description', 'Description ' || cnt,
            'startDate', '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt-1)),
            'endDate', '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt+6))
    )::json
FROM generate_series(1, 10000000) AS t(cnt);

TRUNCATE TABLE auction_jsonb;
ALTER SEQUENCE auction_jsonb_id_seq RESTART;
INSERT INTO auction_jsonb (title, start_date, end_date, item)
SELECT
    'Title ' || cnt,
    '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt-1)),
    '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt+6)),
    JSON_BUILD_OBJECT(
            'type', 'book',
            'genre', 'Genre '||cnt,
            'author', 'Author ' || cnt % 1000,
            'title', 'Title ' || cnt,
            'description', 'Description ' || cnt,
            'startDate', '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt-1)),
            'endDate', '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt+6))
    )::json
FROM generate_series(1, 10000000) AS t(cnt);

TRUNCATE TABLE auction_jsonb_indexed;
ALTER SEQUENCE auction_jsonb_indexed_id_seq RESTART;
INSERT INTO auction_jsonb_indexed (title, start_date, end_date, item)
SELECT
    'Title ' || cnt,
    '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt-1)),
    '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt+6)),
    JSON_BUILD_OBJECT(
            'type', 'book',
            'genre', 'Genre '||cnt,
            'author', 'Author ' || cnt % 1000,
            'title', 'Title ' || cnt,
            'description', 'Description ' || cnt,
            'startDate', '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt-1)),
            'endDate', '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt+6))
    )::json
FROM generate_series(1, 10000000) AS t(cnt);

TRUNCATE TABLE auction_jsonb_gin;
ALTER SEQUENCE auction_jsonb_gin_id_seq RESTART;
INSERT INTO auction_jsonb_gin (title, start_date, end_date, item)
SELECT
    'Title ' || cnt,
    '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt-1)),
    '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt+6)),
    JSON_BUILD_OBJECT(
            'type', 'book',
            'genre', 'Genre '||cnt,
            'author', 'Author ' || cnt % 1000,
            'title', 'Title ' || cnt,
            'description', 'Description ' || cnt,
            'startDate', '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt-1)),
            'endDate', '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt+6))
    )::json
FROM generate_series(1, 10000000) AS t(cnt);

-- the additional columns are generated by postgres (and may not be explicitly assigned a value)
TRUNCATE TABLE auction_generated_fields;
ALTER SEQUENCE auction_generated_fields_id_seq RESTART;
INSERT INTO auction_generated_fields (item)
SELECT
    JSON_BUILD_OBJECT(
            'type', 'book',
            'genre', 'Genre '||cnt,
            'author', 'Author ' || cnt % 1000,
            'title', 'Title ' || cnt,
            'description', 'Description ' || cnt,
            'startDate', '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt-1)),
            'endDate', '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt+6))
    )::json
FROM generate_series(1, 10000000) AS t(cnt);

TRUNCATE TABLE auction_generated_fields_indexed;
ALTER SEQUENCE auction_generated_fields_indexed_id_seq RESTART;
INSERT INTO auction_generated_fields_indexed (item)
SELECT
    JSON_BUILD_OBJECT(
            'type', 'book',
            'genre', 'Genre '||cnt,
            'author', 'Author ' || cnt % 1000,
            'title', 'Title ' || cnt,
            'description', 'Description ' || cnt,
            'startDate', '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt-1)),
            'endDate', '2024-01-01'::timestamp + (INTERVAL '1 minute' * (cnt+6))
    )::json
FROM generate_series(1, 10000000) AS t(cnt);